from .base_prompt import (
    BASE_PEDAGOGICAL_AND_FORMATTING_RULES,
    BASE_PEDAGOGICAL_RULES,
    PROMPT_BUNDLE_VERSION,
)

__all__ = [
    "BASE_PEDAGOGICAL_RULES",
    "BASE_PEDAGOGICAL_AND_FORMATTING_RULES",
    "PROMPT_BUNDLE_VERSION",
]
