from pydantic import BaseModel, Field

from .practice_problem import PracticeProblem


class SectionContent(BaseModel):
    """Content for a single textbook section, generated by the Content Generator node."""

    section_id: str
    hook: str = Field(description="Opening paragraph - felt problem before named solution")
    prerequisites_block: str = Field(
        default="",
        description="Short prerequisite refresher shown before the main explanation",
    )
    plain_explanation: str = Field(description="Concept in plain language, no jargon")
    formal_definition: str = Field(
        description="Precise definition, notation where appropriate"
    )
    worked_example: str = Field(description="Full example, every step explained")
    common_misconception: str = Field(
        description="One thing learners consistently get wrong here"
    )
    practice_problems: list[PracticeProblem] = Field(
        default_factory=list,
        description="Exactly three practice problems with warm, medium, and cold difficulty",
    )
    interview_anchor: str = Field(
        default="",
        description="A short interview-style framing question for the concept",
    )
    think_prompt: str = Field(
        default="",
        description="A reflective prompt asking the learner to pause and reason",
    )
    connection_forward: str = Field(description="One sentence linking to next section")
