from pydantic import BaseModel, Field


class SectionCode(BaseModel):
    """Code example for a textbook section, generated by the Code Generator node."""

    section_id: str
    language: str = Field(default="python", description="'python' for Phase 1")
    code: str = Field(description="Syntactically valid, runnable code")
    explanation: str = Field(description="What to observe when running this")
    expected_output: str = Field(description="What the code prints/returns")
