from pydantic import BaseModel, Field


class SectionContent(BaseModel):
    """Content for a single textbook section, generated by the Content Generator node."""

    section_id: str
    hook: str = Field(description="Opening paragraph - felt problem before named solution")
    plain_explanation: str = Field(description="Concept in plain language, no jargon")
    formal_definition: str = Field(
        description="Precise definition, notation where appropriate"
    )
    worked_example: str = Field(description="Full example, every step explained")
    common_misconception: str = Field(
        description="One thing learners consistently get wrong here"
    )
    connection_forward: str = Field(description="One sentence linking to next section")
