from pydantic import BaseModel, Field


class SectionDiagram(BaseModel):
    """SVG diagram for a textbook section, generated by the Diagram Generator node."""

    section_id: str
    svg_markup: str = Field(description="Complete inline SVG")
    caption: str = Field(description="One sentence describing what the diagram shows")
    diagram_type: str = Field(
        description="e.g. 'number_line', 'function_plot', 'array_trace', 'tree'"
    )
