from __future__ import annotations

import os
from datetime import datetime
from io import BytesIO
from typing import Optional

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas

from ..config import pdf_config


def generate_cover_page(
    textbook_topic: str,
    textbook_level: str,
    group_name: str,
    school_name: str,
    teacher_name: str,
    date: Optional[str] = None,
    textbook_id: Optional[str] = None,
) -> str:
    """
    Generate a text-based cover page.

    Returns: Path to temporary PDF file.
    """
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    # Title
    c.setFont(pdf_config.TITLE_FONT, pdf_config.TITLE_SIZE)
    c.drawCentredString(width / 2, height - 120 * mm, textbook_topic)

    # Level subtitle
    c.setFont(pdf_config.HEADING_FONT, 20)
    c.drawCentredString(width / 2, height - 140 * mm, f"Level: {textbook_level}")

    # Metadata box
    box_top = height - 170 * mm
    box_height = 80 * mm
    box_margin = 60 * mm

    c.setLineWidth(2)
    c.rect(box_margin, box_top - box_height, width - 2 * box_margin, box_height)

    # Metadata content
    c.setFont(pdf_config.BODY_FONT, 14)
    y = box_top - 15 * mm

    metadata_items = [
        ("School:", school_name),
        ("Teacher:", teacher_name),
        ("Date:", date or datetime.now().strftime("%B %d, %Y")),
        ("Group:", group_name or "General"),
    ]

    for label, value in metadata_items:
        c.setFont(pdf_config.HEADING_FONT, 14)
        c.drawString(box_margin + 10 * mm, y, label)
        c.setFont(pdf_config.BODY_FONT, 14)
        c.drawString(box_margin + 40 * mm, y, value)
        y -= 18 * mm

    # Student name field
    c.setFont(pdf_config.HEADING_FONT, 16)
    c.drawString(60 * mm, 80 * mm, "Student Name:")
    c.setLineWidth(1)
    c.line(120 * mm, 78 * mm, width - 60 * mm, 78 * mm)

    # Footer
    c.setFont("Helvetica-Oblique", 10)
    c.drawCentredString(width / 2, 30 * mm, "Generated by Lectio")
    if textbook_id:
        c.setFont("Helvetica", 9)
        c.drawCentredString(width / 2, 25 * mm, f"ID: {textbook_id}")

    c.showPage()
    c.save()

    os.makedirs(pdf_config.TEMP_DIR, exist_ok=True)
    output_path = f"{pdf_config.TEMP_DIR}/cover_{textbook_id or 'temp'}.pdf"

    with open(output_path, "wb") as f:
        f.write(buffer.getvalue())

    return output_path
